services:
  postgres:
    image: postgres:16-alpine
    container_name: fellowship-db
    restart: always
    env_file: ./db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fellowship-net

  backend1:
    image: reetwiz/fellowblogs-backend1-prod:${TAG:-latest}
    container_name: fellowship-backend1
    restart: always
    env_file: ./backend1/.env
    depends_on:
      - postgres
    networks:
      - fellowship-net

  backend2:
    image: reetwiz/fellowblogs-backend2-prod:${TAG:-latest}
    container_name: fellowship-backend2
    restart: always
    env_file: ./backend2/.env
    depends_on:
      - postgres
    networks:
      - fellowship-net

  frontend:
    image: reetwiz/fellowblogs-frontend-prod:${TAG:-latest}
    container_name: fellowship-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - fellowship-net

volumes:
  db_data:

networks:
  fellowship-net:
    driver: bridge