version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: fellowship-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fellowship-net

  backend1:
    image: ${DOCKER_IMAGE_BACKEND1}
    container_name: fellowship-backend1
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT_BACKEND1: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CLIENT: ${DB_CLIENT}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - fellowship-net

  backend2:
    image: ${DOCKER_IMAGE_BACKEND2}
    container_name: fellowship-backend2
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT_BACKEND2: 3001
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CLIENT: ${DB_CLIENT}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - fellowship-net

  frontend:
    image: ${DOCKER_IMAGE_FRONTEND}
    container_name: fellowship-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - fellowship-net

volumes:
  db_data:

networks:
  fellowship-net:
    driver: bridge