name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend1/**'
      - 'backend2/**'
      - 'frontend/**'
      - 'docker-compose.prod.yml'
      - '!**.md'
      - '!**/README.md' 

permissions:
  contents: write 
  packages: write
  pages: write
  id-token: write

jobs:
  changes:
    name: 1. Detect Service Changes
    runs-on: ubuntu-latest
    outputs:
      backend1: ${{ steps.filter.outputs.backend1 }}
      backend2: ${{ steps.filter.outputs.backend2 }}
      frontend: ${{ steps.filter.outputs.frontend }}
      any_changed: ${{ steps.filter.outputs.backend1 == 'true' || steps.filter.outputs.backend2 == 'true' || steps.filter.outputs.frontend == 'true' }}
      repo_name_lc: ${{ steps.repo_name.outputs.lower }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend1:
              - 'backend1/**'
            backend2:
              - 'backend2/**'
            frontend:
              - 'frontend/**'
      - name: Set repo name to lowercase
        id: repo_name
        run: echo "lower=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  prepare:
    name: 2. Prepare Version (for Main only)
    needs: changes
    if: github.ref_name == 'main' && needs.changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      version: ${{ steps.changelog.outputs.version }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    name: 3. Build & Push - ${{ matrix.service }}
    needs: [changes, prepare]
    if: (github.ref_name == 'dev' && needs.changes.outputs.any_changed == 'true') || (github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false')
    runs-on: ${{ matrix.runner }} 
    strategy:
      matrix:
        include:
          - service: backend1
            context: ./backend1
            runner: backend-runner
          - service: backend2
            context: ./backend2
            runner: backend-runner
          - service: frontend
            context: ./frontend
            runner: frontend-runner
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - uses: docker/setup-buildx-action@v3
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.changes.outputs.repo_name_lc }}-${{ matrix.service }}
          tags: |
            type=raw,value=dev,enable=${{ github.ref_name == 'dev' }}
            type=sha,prefix=dev-,format=short,enable=${{ github.ref_name == 'dev' }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=semver,pattern=v{{version}},value=${{ needs.prepare.outputs.version }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ needs.prepare.outputs.version }},enable=${{ github.ref_name == 'main' }}
      - name: Build and push Docker image (if changed)
        id: build
        if: needs.changes.outputs[matrix.service] == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.service }}
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-${{ matrix.service }}
          build-args: |
            ${{ matrix.service == 'frontend' && format('VITE_CLERK_PUBLISHABLE_KEY={0}', vars.VITE_CLERK_PUBLISHABLE_KEY) || '' }}
            ${{ matrix.service == 'frontend' && 'VITE_BACKEND1_BASE_URL=http://backend1:3000' || '' }}
            ${{ matrix.service == 'frontend' && 'VITE_BACKEND2_BASE_URL=http://backend2:3001' || '' }}
      - name: Re-tag and push existing image (if not changed on main)
        if: github.ref_name == 'main' && needs.changes.outputs[matrix.service] == 'false'
        run: |
          PROD_IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.changes.outputs.repo_name_lc }}-${{ matrix.service }}"
          docker pull $PROD_IMAGE_NAME:latest
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | while read tag; do
            docker tag $PROD_IMAGE_NAME:latest "$tag"
            docker push "$tag"
          done
      - name: Upload Build Artifact (Source Code)
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.service }}
          path: ${{ matrix.context }}

  upload-compose-artifact:
    name: 4. Upload Compose Artifact for Release
    needs: prepare
    if: github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: docker-compose-file
          path: docker-compose.prod.yml

  export-images:
    name: 5. Export Docker Images for Release
    needs: [changes, prepare, build-and-push]
    if: github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend1, backend2, frontend]
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Pull and Export Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.changes.outputs.repo_name_lc }}-${{ matrix.service }}"
          IMAGE_TAG="${{ needs.prepare.outputs.tag }}"
          docker pull $IMAGE_NAME:$IMAGE_TAG
          docker save -o image-${{ matrix.service }}.tar $IMAGE_NAME:$IMAGE_TAG
      - name: Upload Image Export as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-export-${{ matrix.service }}
          path: image-${{ matrix.service }}.tar

  scan-images:
    name: 6. Scan Images for Release
    needs: [changes, prepare, build-and-push]
    if: github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend1, backend2, frontend]
    steps:
      - name: Scan image with Trivy and generate HTML report
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.changes.outputs.repo_name_lc }}-${{ matrix.service }}:${{ needs.prepare.outputs.tag }}
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ matrix.service }}
          path: trivy-report.html

  deploy-to-pages:
    name: 7. Deploy Site and Reports to GitHub Pages
    needs: [prepare, scan-images]
    if: github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Build Frontend for GitHub Pages
        run: |
          cd frontend
          yarn install --frozen-lockfile
          VITE_BASE_URL='/reetwiz-fellowblogs-cd/' yarn build
      - name: Download all scan reports
        uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Consolidate Artifacts for Pages
        run: |
          mkdir -p _site/scan
          if [ -d "frontend/dist" ]; then
            cp -r frontend/dist/* _site/
          fi
          CONTENT_B1=$(awk '/<body/,/<\/body>/' reports/trivy-report-backend1/trivy-report.html | sed '1d;$d')
          CONTENT_B2=$(awk '/<body/,/<\/body>/' reports/trivy-report-backend2/trivy-report.html | sed '1d;$d')
          CONTENT_FE=$(awk '/<body/,/<\/body>/' reports/trivy-report-frontend/trivy-report.html | sed '1d;$d')
          cat <<EOF > _site/scan/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Consolidated Trivy Scan Report</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <style>
            body { 
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif; 
              margin: 2em; 
              line-height: 1.5; 
            }
            h1 { 
              border-bottom: 2px solid #eaecef; 
              padding-bottom: 0.3em; 
              font-size: 2em; 
            }
            .tab {
              overflow: hidden;
              border: 1px solid #ccc;
              background-color: #f1f1f1;
              border-radius: 5px 5px 0 0;
            }
            .tab button {
              background-color: inherit;
              float: left;
              border: none;
              outline: none;
              cursor: pointer;
              padding: 14px 16px;
              transition: 0.3s;
              font-size: 17px;
              font-weight: 600;
            }
            .tab button:hover {
              background-color: #ddd;
            }
            .tab button.active {
              background-color: #ccc;
            }
            .tabcontent {
              display: none;
              padding: 12px;
              border: 1px solid #ccc;
              border-top: none;
              border-radius: 0 0 5px 5px;
            }
            .tabcontent table { 
              border-collapse: collapse; 
              margin: 1em 0; 
              width: 100%; 
            }
            .tabcontent th, .tabcontent td { 
              border: 1px solid #ddd; 
              padding: 8px; 
              text-align: left; 
            }
            .tabcontent th { 
              background-color: #f2f2f2; 
            }
          </style>
          </head>
          <body>
          <h1>Consolidated Trivy Scan Report for Release ${{ needs.prepare.outputs.tag }}</h1>
          <div class="tab">
            <button class="tablinks active" onclick="openTab(event, 'Backend1')">Backend 1</button>
            <button class="tablinks" onclick="openTab(event, 'Backend2')">Backend 2</button>
            <button class="tablinks" onclick="openTab(event, 'Frontend')">Frontend</button>
          </div>
          <div id="Backend1" class="tabcontent" style="display:block;">
            <h2>Backend1 Scan Results</h2>
            ${CONTENT_B1}
          </div>
          <div id="Backend2" class="tabcontent">
            <h2>Backend2 Scan Results</h2>
            ${CONTENT_B2}
          </div>
          <div id="Frontend" class="tabcontent">
            <h2>Frontend Scan Results</h2>
            ${CONTENT_FE}
          </div>
          <script>
          function openTab(evt, tabName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
              tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) {
              tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.className += " active";
          }
          </script>
          </body>
          </html>
          EOF
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
  deploy-to-vm:
    name: 8. Deploy to Production VM
    needs: [build-and-push]
    if: github.ref_name == 'main'
    runs-on: backend-runner
    steps:
      - name: Trigger Deployment on VM
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }}
          REMOTE_USER: ${{ secrets.VM_USERNAME }}
          TARGET: "/home/reetwiz/fellowblogs"
          SCRIPT_AFTER: |
            set -e
            cd /home/reetwiz/fellowblogs
            echo "--- Pulling latest images ---"
            docker-compose pull
            echo "--- Restarting services ---"
            docker-compose up -d --remove-orphans
            echo "--- Cleaning up old images ---"
            docker image prune -af

  release:
    name: 9. Create GitHub Release
    needs: [prepare, deploy-to-vm, export-images, upload-compose-artifact, scan-images]
    if: github.ref_name == 'main' && needs.prepare.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts for release
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: Release ${{ needs.prepare.outputs.tag }}
          body: ${{ needs.prepare.outputs.clean_changelog }}
          files: |
            release-artifacts/docker-compose-file/docker-compose.prod.yml
            release-artifacts/build-artifact-*/*.zip
            release-artifacts/trivy-report-*/*.html
            release-artifacts/docker-image-export-*/*.tar