name: Manual Deploy to VM (Test Connection)

on:
  workflow_dispatch:

jobs:
  test-vm-connection:
    name: Test SSH Connection and Write Permission
    runs-on: backend-runner

    steps:
      - name: SSH into VM and create a test file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/reetwiz/fellowblogs/
            echo "Creating a test file to verify connection..."
            echo "File created successfully by GitHub Actions on $(date)" > github_actions_test.txt
            echo "Test file created. Directory contents:"
            ls -l
